_meta:
  function_prefix: Func # call your functions with Func:: like Func::decrypt "arg1" "arg2"
  custom_functions:
    getCfnOutput:
      exec: |
        aws --region $1 cloudformation describe-stacks --stack-name $2 | 
        jq -r '.Stacks[] | select(.StackName == "$2") | .Outputs[] | select(.OutputKey == "$3") | .OutputValue'
  public_keys:
    dev20230604: |
      eyJwcmltYXJ5S2V5SWQiOjYxMzg0NDUsImtleSI6W3sia2V5R
      GF0YSI6eyJ0eXBlVXJsIjoidHlwZS5nb29nbGVhcGlzLmNvbS
      9nb29nbGUuY3J5cHRvLnRpbmsuSHBrZVB1YmxpY0tleSIsInZ
      hbHVlIjoiRWdZSUFSQUJHQUlhSUpPOWpZOXVhVkljd2NsNEV1
      S1lqUmFDSklzVktkR29DNmFrZFlUUDFWeEsiLCJrZXlNYXRlc
      mlhbFR5cGUiOiJBU1lNTUVUUklDX1BVQkxJQyJ9LCJzdGF0dX
      MiOiJFTkFCTEVEIiwia2V5SWQiOjYxMzg0NDUsIm91dHB1dFB
      yZWZpeFR5cGUiOiJUSU5LIn1dfQo=

environments:
  dev:
    locals:
      region: us-west-2
    exports:
      REGION: Func::Eval '../locals/region'
      DB_USERNAME: "db"
      DB_PASSWORD: "db"
      DB_PORT: "83306"
  staging:
    REGION: "us-west-2"
    DB_USERNAME: "db"
    DB_PASSWORD: 
      Func::decrypt:
      - pubkey: dev20230604
      - encrypted_string: 'AQBdqk2Z9iY1km3gT8zffMANtgOy12liTUyMrTdXZj1CCN3nZ8bdgs0hKLnA8sEI/fhyXldQjksanQZZ'
    DB_PORT: 
      Func::cfn:
      - region: 'us-west-2'
      - environment: 'staging'
      - export_name: "db_port"
  production:
    REGION: "us-west-2"
    DB_USERNAME: "db"
#    DB_PASSWORD: '{{ decrypt "dev20230604" "c3VwZXJTZWNyZXRQcm9k" }}'
    DB_PORT: "3306"

